name: Build NixOS Akkoma Server ISO

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Manueller Start möglich

jobs:
  build-iso:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Setup Nix
      uses: cachix/install-nix-action@v23
      with:
        nix_path: nixpkgs=channel:nixos-23.11
        extra_nix_config: |
          experimental-features = nix-command flakes
          max-jobs = auto
          cores = 0
          gc-keep-outputs = true
          gc-keep-derivations = true
          
    - name: Setup Cachix Cache
      uses: cachix/cachix-action@v12
      with:
        name: nix-community
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        
    - name: Build ISO Image
      run: |
        echo "=== Building NixOS ISO with Akkoma + Jitsi ==="
        nix-build '<nixpkgs/nixos>' \
          -A config.system.build.isoImage \
          -I nixos-config=./iso-image.nix \
          --out-link result-iso \
          --max-jobs auto \
          --cores 0
          
        echo "=== ISO Build completed ==="
        ls -la result-iso/iso/
        
    - name: Build QCOW2 Image
      run: |
        echo "=== Building QCOW2 Image for Cloud Deployment ==="
        nix-build '<nixpkgs/nixos>' \
          -A config.system.build.qcow2Image \
          -I nixos-config=./configuration.nix \
          --out-link result-qcow2 \
          --max-jobs auto \
          --cores 0
          
        echo "=== QCOW2 Build completed ==="
        ls -la result-qcow2/
        
    - name: Upload ISO Artifact
      uses: actions/upload-artifact@v4
      with:
        name: nixos-akkoma-iso
        path: result-iso/iso/*.iso
        retention-days: 30
        
    - name: Upload QCOW2 Artifact
      uses: actions/upload-artifact@v4
      with:
        name: nixos-akkoma-qcow2
        path: result-qcow2/*.qcow2
        retention-days: 30
        
    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          result-iso/iso/*.iso
          result-qcow2/*.qcow2
        generate_release_notes: true
        draft: false
        prerelease: false
